set(SERVUS_MATURITY "EP")
set(SERVUS_DESCRIPTION "C++ network oriented utilities including a zeroconf implementation")
set(SERVUS_GIT_ROOT_URL "git@github.com:HBPVIS/Servus.git")
set(SERVUS_PACKAGE_URL "")
set(SERVUS_CI_URL "git@travis-ci.org:HBPVIS/Servus")
set(SERVUS_CI_PNG "git@travis-ci.org:HBPVIS/Servus.png")
set(SERVUS_ISSUES_URL "git@github.com:HBPVIS/Servus/issues")
