# Site settings
title: HBP Visualization Software Directory
organization: HBPVis

# Build settings
markdown: kramdown

# Do not exclude doxygen files starting with an underscore
include: [ _*.html ]

# Link to other documentation pages
seealso: bluebrain.github.io

# The collection of documentation metadata
collections:
  - projects
