set(ZEROBUF_MATURITY "EP")
set(ZEROBUF_DESCRIPTION "")
set(ZEROBUF_GIT_ROOT_URL "https://github.com/favreau/ZeroBuf.git")
set(ZEROBUF_PACKAGE_URL "")
set(ZEROBUF_CI_URL "https://travis-ci.org/favreau/ZeroBuf")
set(ZEROBUF_CI_PNG "https://travis-ci.org/favreau/ZeroBuf.png")
set(ZEROBUF_ISSUES_URL "https://github.com/favreau/ZeroBuf/issues")
