set(ZEROBUF_MATURITY "EP")
set(ZEROBUF_DESCRIPTION "")
set(ZEROBUF_GIT_ROOT_URL "git@github.com:HBPVIS/ZeroBuf")
set(ZEROBUF_PACKAGE_URL "")
set(ZEROBUF_CI_URL "git@travis-ci.org:HBPVIS/ZeroBuf")
set(ZEROBUF_CI_PNG "git@travis-ci.org:HBPVIS/ZeroBuf.png")
set(ZEROBUF_ISSUES_URL "git@github.com:HBPVIS/ZeroBuf")
