set(ZEROEQ_MATURITY "EP")
set(ZEROEQ_DESCRIPTION "")
set(ZEROEQ_GIT_ROOT_URL "https://github.com/HBPVIS/ZeroEQ.git")
set(ZEROEQ_PACKAGE_URL "")
set(ZEROEQ_CI_URL "https://travis-ci.org/HBPVIS/ZeroEQ")
set(ZEROEQ_CI_PNG "https://travis-ci.org/HBPVIS/ZeroEQ.png")
set(ZEROEQ_ISSUES_URL "https://github.com/HBPVIS/ZeroEQ/issues")
