zeq: zeq::http::Server Class Reference
zeq::http::Server Class Reference
Serves HTTP GET and PUT requests for servus::Serializable objects.
#include <server.h>
Public Member Functions
Object registration for PUT and GET requests
bool add (servus::Serializable &object)
Subscribe and register the given object.
bool remove (const servus::Serializable &object)
Unsubscribe and unregister the given object.
bool subscribe (servus::Serializable &object)
Subscribe a serializable object to receive updates from HTTP PUT requests.
bool unsubscribe (const servus::Serializable &object)
Unsubscribe the given object to stop applying updates.
bool register_ (servus::Serializable &object)
Subscribe a serializable object to serve HTTP GET requests.
bool unregister (const servus::Serializable &object)
Unsubscribe the given object for GET requests.
Public Member Functions inherited from zeq::Receiver
Receiver ()
Create a new standalone receiver.
Receiver (Receiver &shared)
Create a shared receiver.
virtual ~Receiver ()
Destroy this receiver.
bool receive (const uint32_t timeout=TIMEOUT_INDEFINITE)
Receive at least one event from all shared receivers.
Setup
Server (const URI &uri, Receiver &shared)
Construct a new HTTP server.
Server (const URI &uri)
Server (Receiver &shared)
Server ()
Server (Server &shared)
virtual ~Server ()
const servus::URI & getURI () const
Get the publisher URI.
static std::unique_ptr< Server > parse (int argc, const char *argv[])
Create a new Server when requested.
static std::unique_ptr< Server > parse (int argc, const char *argv[], Receiver &shared)
Additional Inherited Members
Protected Member Functions inherited from zeq::Receiver
virtual void update ()
Update the internal connection list.
void * getZMQContext ()
Detailed Description
Serves HTTP GET and PUT requests for servus::Serializable objects.
Behaves semantically like a Publisher (for GET) and Subscriber (for PUT), except uses HTTP with JSON payload as the protocol. Requests are served synchronously (as per HTTP spec). Objects are available under their Serializable::getTypeName(), with '::' replaced by '/'. The REST API is case insensitive. For example, zerobuf::render::Camera is served at 'GET|PUT [uri]/zerobuf/render/camera'.
Not thread safe.
Example:
/* Copyright (c) 2016, Human Brain Project
 *                     Stefan.Eilemann@epfl.ch
 */
#define BOOST_TEST_MODULE http_server
#include <zeq/http/server.h>
#include <zeq/subscriber.h>
#include <zeq/uri.h>
#include <zmq.h>
#include <servus/serializable.h>
#include <servus/uri.h>
#include <boost/test/unit_test.hpp>
#include <thread>
namespace
{
const std::string jsonGet("Not JSON, just want to see that the is data a-ok");
const std::string jsonPut("See what my stepbrother jsonGet says");
const std::string error400("HTTP/1.0 400 Bad Request\r\nContent-Length: 28\r\n\r\nHTTP/1.0 400 Bad Request\r\n\r\n");
const std::string error404("HTTP/1.0 404 Not Found\r\nContent-Length: 26\r\n\r\nHTTP/1.0 404 Not Found\r\n\r\n");
const std::string error405("HTTP/1.0 405 Method Not Allowed\r\nContent-Length: 35\r\n\r\nHTTP/1.0 405 Method Not Allowed\r\n\r\n");
const std::string error411("HTTP/1.0 411 Length Required\r\nContent-Length: 32\r\n\r\nHTTP/1.0 411 Length Required\r\n\r\n");
class Foo : public servus::Serializable
{
public:
    Foo() { _notified = false; }
    void setNotified() { _notified = true; }
    bool getNotified() const { return _notified; }
private:
    std::string getTypeName() const final { return "test::Foo"; }
    virtual zeq::uint128_t getTypeIdentifier() const final
        { return servus::make_uint128( getTypeName( )); }
    bool _fromJSON( const std::string& json ) final
    {
        return jsonPut == json;
    }
    std::string _toJSON() const final
    {
        return jsonGet;
    }
    bool _notified;
};
class Client
{
public:
    Client( const servus::URI& uri )
        : _ctx( ::zmq_ctx_new ( ))
        , _socket( ::zmq_socket( _ctx, ZMQ_STREAM ))
    {
        if( ::zmq_connect( _socket, std::to_string( uri ).c_str( )) == -1 )
            throw std::runtime_error( "Connect failed" );
    }
    ~Client()
    {
        if( _socket )
            ::zmq_close( _socket );
        if( _ctx )
            ::zmq_ctx_destroy( _ctx );
    }
    void test( const std::string& request, const std::string& expected,
               const int line )
    {
        // Get server identity
        uint8_t id[256];
        size_t idSize = sizeof( id );
        BOOST_CHECK_EQUAL( zmq_getsockopt( _socket, ZMQ_IDENTITY, id, &idSize ),
                           0 );
        if( ::zmq_send( _socket, id, idSize, ZMQ_SNDMORE ) != int( idSize ) ||
            ::zmq_send( _socket, request.c_str(), request.length(), 0 ) !=
            int( request.length( )))
        {
            throw std::runtime_error( "Send failed" );
        }
        std::string response;
        while( response.size() < expected.size( ))
        {
            if( ::zmq_recv( _socket, id, idSize, 0 ) != int( idSize ))
                throw std::runtime_error( "Recv failed" );
            char msg[256];
            const int read = ::zmq_recv( _socket, msg, sizeof( msg ), 0 );
            BOOST_REQUIRE( read > 0 );
            response.append( msg, read );
        }
        BOOST_CHECK_MESSAGE( response == expected,
                             "At l." + std::to_string( line ) + ": " + response +
                             " != " + expected);
    }
private:
    void* _ctx;
    void* _socket;
};
}
BOOST_AUTO_TEST_CASE(construction)
{
    zeq::http::Server server1;
    BOOST_CHECK_NE( server1.getURI().getHost(), "" );
    BOOST_CHECK_NE( server1.getURI().getHost(), "*" );
    BOOST_CHECK_NE( server1.getURI().getPort(), 0 );
    const zeq::URI uri( "tcp://" );
    zeq::http::Server server2( uri );
    zeq::http::Server server3( uri );
    BOOST_CHECK_NE( server2.getURI(), server3.getURI( ));
    BOOST_CHECK_NE( server2.getURI().getPort(), 0 );
    BOOST_CHECK_THROW( zeq::http::Server( server2.getURI( )),
                       std::runtime_error );
}
BOOST_AUTO_TEST_CASE(construction_argv_host_port)
{
    const char* app = boost::unit_test::framework::master_test_suite().argv[0];
    const char* argv[] = { app, "--zeq-http-server", "127.0.0.1:0" };
    const int argc = sizeof(argv)/sizeof(char*);
    std::unique_ptr< zeq::http::Server > server1 =
            zeq::http::Server::parse( argc, argv );
    BOOST_REQUIRE( server1 );
    BOOST_CHECK_EQUAL( server1->getURI().getHost(), "127.0.0.1" );
    BOOST_CHECK_NE( server1->getURI().getPort(), 0 );
    zeq::Subscriber shared;
    std::unique_ptr< zeq::http::Server > server2 =
            zeq::http::Server::parse( argc, argv, shared );
    BOOST_REQUIRE( server2 );
    BOOST_CHECK_EQUAL( server2->getURI().getHost(), "127.0.0.1" );
    BOOST_CHECK_NE( server2->getURI().getPort(), 0 );
}
BOOST_AUTO_TEST_CASE(construction_argv)
{
    const char* app = boost::unit_test::framework::master_test_suite().argv[0];
    const char* argv[] = { app, "--zeq-http-server" };
    const int argc = sizeof(argv)/sizeof(char*);
    std::unique_ptr< zeq::http::Server > server1 =
            zeq::http::Server::parse( argc, argv );
    BOOST_REQUIRE( server1 );
    BOOST_CHECK( !server1->getURI().getHost().empty( ));
    BOOST_CHECK_NE( server1->getURI().getPort(), 0 );
    zeq::Subscriber shared;
    std::unique_ptr< zeq::http::Server > server2 =
            zeq::http::Server::parse( argc, argv, shared );
    BOOST_REQUIRE( server2 );
    BOOST_CHECK( !server2->getURI().getHost().empty( ));
    BOOST_CHECK_NE( server2->getURI().getPort(), 0 );
}
BOOST_AUTO_TEST_CASE(construction_empty_argv)
{
    const char* app = boost::unit_test::framework::master_test_suite().argv[0];
    const char* argv[] = { app };
    const int argc = sizeof(argv)/sizeof(char*);
    std::unique_ptr< zeq::http::Server > server1 =
            zeq::http::Server::parse( argc, argv );
    BOOST_CHECK( !server1 );
    zeq::Subscriber shared;
    std::unique_ptr< zeq::http::Server > server2 =
            zeq::http::Server::parse( argc, argv, shared );
    BOOST_CHECK( !server2 );
}
BOOST_AUTO_TEST_CASE(registration)
{
    zeq::http::Server server;
    Foo foo;
    BOOST_CHECK( server.register_( foo ));
    BOOST_CHECK( !server.register_( foo ));
    BOOST_CHECK( server.unregister( foo ));
    BOOST_CHECK( !server.unregister( foo ));
    BOOST_CHECK( server.subscribe( foo ));
    BOOST_CHECK( !server.subscribe( foo ));
    BOOST_CHECK( server.unsubscribe( foo ));
    BOOST_CHECK( !server.unsubscribe( foo ));
    BOOST_CHECK( server.add( foo ));
    BOOST_CHECK( !server.add( foo ));
    BOOST_CHECK( server.remove( foo ));
    BOOST_CHECK( !server.remove( foo ));
}
BOOST_AUTO_TEST_CASE(get)
{
    bool running = true;
    zeq::http::Server server;
    Foo foo;
    foo.setRequestedFunction( [&]{ foo.setNotified(); });
    server.register_( foo );
    std::thread thread( [ & ]() { while( running ) server.receive( 100 ); });
    Client client( server.getURI( ));
    client.test( "GET /unknown HTTP/1.0\r\n\r\n", error404, __LINE__ );
    BOOST_CHECK( !foo.getNotified( ));
    client.test( "GET /test/Foo HTTP/1.0\r\n\r\n",
                 std::string( "HTTP/1.0 200 OK\r\nContent-Length: 48\r\n\r\n" )+
                 jsonGet, __LINE__ );
    BOOST_CHECK( foo.getNotified( ));
    running = false;
    thread.join();
}
BOOST_AUTO_TEST_CASE(shared)
{
    bool running = true;
    zeq::Subscriber subscriber;
    zeq::http::Server server1( subscriber );
    zeq::http::Server server2( server1 );
    Foo foo;
    server2.register_( foo );
    std::thread thread( [ & ]() { while( running ) subscriber.receive( 100 );});
    Client client1( server1.getURI( ));
    Client client2( server2.getURI( ));
    client1.test( "GET /test/Foo HTTP/1.0\r\n\r\n", error404, __LINE__ );
    client2.test( "GET /test/Foo HTTP/1.0\r\n\r\n",
                  std::string( "HTTP/1.0 200 OK\r\nContent-Length: 48\r\n\r\n" ) +
                  jsonGet, __LINE__ );
    running = false;
    thread.join();
}
BOOST_AUTO_TEST_CASE(put)
{
    bool running = true;
    zeq::http::Server server;
    Foo foo;
    foo.setUpdatedFunction( [&]{ foo.setNotified(); });
    server.subscribe( foo );
    std::thread thread( [ & ]() { while( running ) server.receive( 100 ); });
    Client client( server.getURI( ));
    client.test( std::string( "PUT /test/Foo HTTP/1.0\r\n\r\n" ) + jsonPut,
                 error411, __LINE__ );
    client.test(
        std::string( "PUT /test/Foo HTTP/1.0\r\nContent-Length: 3\r\n\r\nFoo" ),
        error400, __LINE__ );
    client.test( std::string( "PUT /test/Bar HTTP/1.0\r\nContent-Length: " ) +
                 std::to_string( jsonPut.length( )) + "\r\n\r\n" + jsonPut,
                 error404, __LINE__ );
    BOOST_CHECK( !foo.getNotified( ));
    client.test( std::string( "PUT /test/Foo HTTP/1.0\r\nContent-Length: " ) +
                 std::to_string( jsonPut.length( )) + "\r\n\r\n" + jsonPut,
                 std::string( "HTTP/1.0 200 OK\r\nContent-Length: 0\r\n\r\n" ),
                 __LINE__);
    BOOST_CHECK( foo.getNotified( ));
    running = false;
    thread.join();
}
BOOST_AUTO_TEST_CASE(post)
{
    bool running = true;
    zeq::http::Server server;
    Foo foo;
    server.register_( foo );
    std::thread thread( [ & ]() { while( running ) server.receive( 100 ); });
    Client client( server.getURI( ));
    client.test( std::string( "POST /test/Foo HTTP/1.0\r\nContent-Length: " ) +
                 std::to_string( jsonPut.length( )) + "\r\n\r\n" + jsonPut,
                 error405, __LINE__ );
    running = false;
    thread.join();
}
BOOST_AUTO_TEST_CASE(largeGet)
{
    bool running = true;
    zeq::http::Server server;
    Foo foo;
    server.register_( foo );
    std::thread thread( [ & ]() { while( running ) server.receive( 100 ); });
    Client client( server.getURI( ));
    client.test( "GET" + std::string( 4096, ' ' ) +
                 "/test/Foo HTTP/1.0\r\n\r\n",
                 std::string( "HTTP/1.0 200 OK\r\nContent-Length: 48\r\n\r\n" )+
                 jsonGet, __LINE__ );
    running = false;
    thread.join();
}
BOOST_AUTO_TEST_CASE(garbage)
{
    bool running = true;
    zeq::http::Server server;
    std::thread thread( [ & ]() { while( running ) server.receive( 100 ); });
    Client client( server.getURI( ));
    client.test( "ramble mumble foo bar", "", __LINE__ );
    running = false;
    thread.join();
}
BOOST_AUTO_TEST_CASE(urlcasesensitivity)
{
    bool running = true;
    zeq::http::Server server;
    Foo foo;
    server.register_( foo );
    std::thread thread( [ & ]() { while( running ) server.receive( 100 ); });
    Client client( server.getURI( ));
    client.test( "GET" + std::string( 4096, ' ' ) + "/TEST/FOO HTTP/1.0\r\n\r\n",
                 std::string( "HTTP/1.0 200 OK\r\nContent-Length: 48\r\n\r\n" ) +
                 jsonGet, __LINE__ );
    client.test( "GET" + std::string( 4096, ' ' ) + "/test/foo HTTP/1.0\r\n\r\n",
                 std::string( "HTTP/1.0 200 OK\r\nContent-Length: 48\r\n\r\n" ) +
                 jsonGet, __LINE__ );
    running = false;
    thread.join();
}
Definition at line 31 of file server.h.
Constructor & Destructor Documentation
zeq::http::Server::Server (const URI & uri, Receiver & shared)
Construct a new HTTP server.
To process requests on the incoming port, call receive(). If no hostname is given, the server listens on all interfaces (INADDR_ANY). If no port is given, the server selects a random port. Use getURI() to retrieve the chosen parameters.
Parameters
uri The server address in the form "[tcp://][hostname][:port]"
shared a shared receiver, see Receiver constructor.
Exceptions
std::runtime_error on malformed URI or connection issues.
Member Function Documentation
bool zeq::http::Server::add (servus::Serializable & object) inline
Subscribe and register the given object.
Definition at line 86 of file server.h.
References register_(), and subscribe().
const servus::URI& zeq::http::Server::getURI () const
Get the publisher URI.
Contains the used hostname and port, if none where given in the constructor uri.
Returns
the publisher URI.
Todo:
change signature to return zeq::URI, needs downstream project adaptions. Also make zeq::URI(const servus::URI& from) explicit.
static std::unique_ptr< Server > zeq::http::Server::parse (int argc, const char * argv[]) static
Create a new Server when requested.
The creation and parameters depend on the following command line parameters:
–zeq-http-server [host][:port]: Enable the server. The optional parameters configure the web server, running by default on INADDR_ANY and a randomly chosen port
bool zeq::http::Server::register_ (servus::Serializable & object)
Subscribe a serializable object to serve HTTP GET requests.
Every request will be directly handled during receive() by using toJSON(). To track updates on the object, the serializable's received function is called accordingly.
The subscribed object instance has to be valid until unregister().
Parameters
object the object to serve during receive()
Returns
true if subscription was successful, false otherwise
Referenced by add().
bool zeq::http::Server::remove (const servus::Serializable & object) inline
Unsubscribe and unregister the given object.
Definition at line 90 of file server.h.
References unregister(), and unsubscribe().
bool zeq::http::Server::subscribe (servus::Serializable & object)
Subscribe a serializable object to receive updates from HTTP PUT requests.
Every update will be directly applied on the object during receive() using fromJSON(). To track updates on the object, the serializable's updated function is called accordingly.
The subscribed object instance has to be valid until unsubscribe().
Parameters
object the object to update on receive()
Returns
true if subscription was successful, false otherwise
Referenced by add().
bool zeq::http::Server::unregister (const servus::Serializable & object)
Unsubscribe the given object for GET requests.
Referenced by remove().
bool zeq::http::Server::unsubscribe (const servus::Serializable & object)
Unsubscribe the given object to stop applying updates.
Referenced by remove().
The documentation for this class was generated from the following file:
server.h