set(ZEQ_MATURITY "EP")
set(ZEQ_DESCRIPTION "")
set(ZEQ_GIT_ROOT_URL "https://github.com/HBPVIS/ZeroEQ.git")
set(ZEQ_PACKAGE_URL "")
set(ZEQ_CI_URL "https://travis-ci.org/HBPVIS/ZeroEQ")
set(ZEQ_CI_PNG "https://travis-ci.org/HBPVIS/ZeroEQ.png")
set(ZEQ_ISSUES_URL "https://github.com/HBPVIS/ZeroEQ/issues")
