set(ZEQ_MATURITY "EP")
set(ZEQ_DESCRIPTION "")
set(ZEQ_GIT_ROOT_URL "https://github.com/HBPVIS/zeq.git")
set(ZEQ_PACKAGE_URL "")
set(ZEQ_CI_URL "https://travis-ci.org/HBPVIS/zeq")
set(ZEQ_CI_PNG "https://travis-ci.org/HBPVIS/zeq.png")
set(ZEQ_ISSUES_URL "https://github.com/HBPVIS/zeq/issues")
