set(LEXIS_MATURITY "EP")
set(LEXIS_DESCRIPTION "Vocabulary of events and shared objects for BBP and HBP software")
set(LEXIS_GIT_ROOT_URL "https://github.com/HBPVIS/Lexis.git")
set(LEXIS_PACKAGE_URL "")
set(LEXIS_CI_URL "https://travis-ci.org/HBPVIS/Lexis")
set(LEXIS_CI_PNG "https://travis-ci.org/HBPVIS/Lexis.png")
set(LEXIS_ISSUES_URL "https://github.com/HBPVIS/Lexis/issues")
